# -*- coding: utf-8 -*-
"""生成 en_dict.json：常用中英对照词典（v0.4.8 云端英文翻译）"""
import json

# 高频单字英译（覆盖一级/二级简码常用字 + 常见字）
SINGLE = {
    "一":"one; a", "二":"two", "三":"three", "四":"four", "五":"five", "六":"six",
    "七":"seven", "八":"eight", "九":"nine", "十":"ten", "百":"hundred", "千":"thousand",
    "万":"ten thousand", "人":"person; people", "口":"mouth", "日":"sun; day", "月":"moon; month",
    "白":"white", "禾":"grain", "言":"speech; words", "立":"stand", "水":"water", "火":"fire",
    "之":"of; it", "王":"king", "土":"soil; earth", "大":"big; large", "木":"wood; tree",
    "工":"work; worker", "目":"eye", "又":"again; also", "子":"child; son", "女":"woman; female",
    "刀":"knife", "力":"power; force", "也":"also; too", "耳":"ear", "手":"hand", "心":"heart",
    "山":"mountain", "田":"field", "马":"horse", "虫":"insect", "舟":"boat", "金":"gold; metal",
    "石":"stone", "皮":"skin", "龙":"dragon", "厂":"factory", "犬":"dog", "广":"wide; broad",
    "尸":"corpse", "弓":"bow", "己":"oneself", "巴":"bar; hope", "幺":"tiny", "方":"square; direction",
    "文":"text; culture", "斤":"jin (unit)", "米":"rice; meter", "白勺":"spoon", "门":"door; gate",
    "车":"car; vehicle", "戈":"dagger-axe", "比":"compare; ratio", "瓦":"tile; watt", "止":"stop",
    "父":"father", "母":"mother", "爷":"grandpa", "奶":"milk; grandma", "哥":"elder brother",
    "姐":"elder sister", "弟":"younger brother", "妹":"younger sister", "爸":"dad; father",
    "妈":"mom; mother", "中":"middle; China", "国":"country; nation", "华":"China; splendid",
    "共":"common; together", "党":"party", "军":"army; military", "民":"people; citizens",
    "政":"politics; government", "府":"government; mansion", "法":"law; method", "治":"rule; govern",
    "经":"pass; manage", "济":"aid; benefit", "贸":"trade", "易":"easy; change", "商":"business; commerce",
    "业":"industry; business", "企":"enterprise", "家":"home; family", "学":"learn; study",
    "校":"school", "生":"life; birth; student", "师":"teacher; master", "教":"teach; education",
    "育":"educate; nurture", "文":"culture; text", "明":"bright; clear", "科":"science; subject",
    "技":"skill; technology", "术":"art; technique", "数":"number; several", "据":"according; evidence",
    "算":"calculate; compute", "机":"machine; opportunity", "云":"cloud", "端":"end; terminal",
    "网":"net; network", "络":"network", "信":"letter; trust", "息":"breath; information",
    "智":"wisdom; smart", "能":"able; can; energy", "工":"work; worker", "业":"industry",
    "农":"agriculture; farmer", "医":"medicine; doctor", "药":"medicine; drug", "院":"yard; institute",
    "电":"electricity; lightning", "话":"words; speech; call", "视":"see; look at", "屏":"screen",
    "幕":"curtain; screen", "脑":"brain", "键":"key; keyboard", "盘":"plate; tray; disk",
    "鼠":"mouse; rat", "标":"mark; target", "软":"soft", "硬":"hard", "件":"piece; item; component",
    "程":"process; journey; procedure", "序":"order; sequence", "码":"code; yard", "编":"compile; edit; weave",
    "译":"translate", "语":"language; words", "言":"speech; words", "词":"word; term",
    "句":"sentence", "章":"chapter; seal", "篇":"piece; sheet", "页":"page",
    "图":"picture; chart; plan", "像":"image; likeness", "片":"piece; film", "影":"shadow; image; film",
    "声":"sound; voice", "音":"sound; tone", "乐":"music; happy", "歌":"song; sing",
    "舞":"dance", "戏":"play; drama; show", "剧":"drama; play", "品":"product; article; quality",
    "牌":"card; brand; sign", "名":"name; famous", "字":"character; word; letter", "号":"number; mark; title",
    "版":"edition; plate", "权":"right; power", "利":"profit; benefit; sharp", "益":"benefit; advantage",
    "价":"price; value", "值":"value; worth", "钱":"money", "币":"currency; coin", "银":"silver; bank",
    "行":"go; bank; line", "存":"save; deposit; exist", "取":"take; get; fetch", "款":"money; paragraph",
    "收":"receive; collect", "支":"support; pay; branch", "付":"pay; give", "账":"account; debt",
    "单":"single; list; bill", "票":"ticket; vote; bill", "券":"coupon; certificate", "卡":"card",
    "费":"fee; cost; spend", "税":"tax; duty", "险":"danger; risk; insurance", "保":"protect; ensure; insurance",
    "险":"danger; risk", "投":"throw; invest", "资":"capital; resources", "股":"share; stock; thigh",
    "券":"bond; certificate", "融":"melt; finance", "通":"through; open; communicate", "达":"reach; arrive",
    "速":"speed; fast", "度":"degree; measure", "量":"quantity; amount; measure", "质":"quality; matter",
    "准":"accurate; standard; allow", "标":"mark; standard", "证":"prove; certificate; evidence",
    "明":"bright; clear; explain", "确":"sure; exact; firm", "实":"real; solid; fruit", "际":"border; occasion; inter-",
    "真":"true; real; genuine", "假":"false; fake; holiday", "优":"excellent; superior", "良":"good; fine",
    "好":"good; fine; well", "坏":"bad; broken", "美":"beautiful; America", "丽":"beautiful", "丑":"ugly; clown",
    "新":"new; fresh", "旧":"old; used", "高":"high; tall", "低":"low", "长":"long; grow; chief",
    "短":"short; brief", "宽":"wide; broad", "窄":"narrow", "厚":"thick; kind", "薄":"thin; slight",
    "深":"deep; profound", "浅":"shallow; light", "轻":"light; gentle", "重":"heavy; important; repeat",
    "快":"fast; quick; happy", "慢":"slow", "早":"early; morning", "晚":"late; evening; night",
    "春":"spring", "夏":"summer", "秋":"autumn; fall", "冬":"winter", "冷":"cold; cool", "热":"hot; heat",
    "温":"warm; temperature", "凉":"cool; cold", "晴":"fine; clear (weather)", "雨":"rain", "雪":"snow",
    "风":"wind; style", "雷":"thunder", "电":"electricity; lightning", "阴":"shade; overcast; yin",
    "阳":"sun; yang", "天":"sky; heaven; day", "地":"earth; ground; land", "海":"sea; ocean", "河":"river",
    "江":"river (Yangtze)", "湖":"lake", "洋":"ocean; foreign", "岛":"island", "山":"mountain; hill",
    "林":"forest; woods", "森":"forest; woods", "树":"tree; plant", "草":"grass; straw", "花":"flower; spend",
    "果":"fruit; result; effect", "瓜":"melon; gourd", "菜":"vegetable; dish", "饭":"meal; rice", "肉":"meat",
    "鱼":"fish", "虾":"shrimp", "蟹":"crab", "牛":"ox; cow; cattle", "羊":"sheep; goat", "猪":"pig",
    "狗":"dog", "猫":"cat", "鸡":"chicken; rooster", "鸭":"duck", "鸟":"bird", "兔":"rabbit",
    "虎":"tiger", "狼":"wolf", "熊":"bear", "猴":"monkey", "象":"elephant; image; like",
    "鹿":"deer", "豹":"leopard", "狮":"lion", "龙":"dragon", "凤":"phoenix", "头":"head; first; top",
    "脸":"face", "眼":"eye", "眉":"eyebrow", "鼻":"nose", "嘴":"mouth; beak", "牙":"tooth; ivory",
    "舌":"tongue", "耳":"ear", "发":"hair; send; develop", "须":"beard; must", "肩":"shoulder",
    "背":"back; carry", "腰":"waist", "腿":"leg", "脚":"foot; base", "手":"hand", "臂":"arm",
    "指":"finger; point", "掌":"palm; control", "胸":"chest; bosom", "腹":"abdomen; belly",
    "肚":"belly; stomach", "胃":"stomach", "肠":"intestine", "肝":"liver", "肺":"lung", "心":"heart",
    "肾":"kidney", "血":"blood", "肉":"meat; flesh", "骨":"bone", "皮":"skin; leather", "毛":"hair; fur; feather",
    "衣":"clothes; clothing", "服":"clothes; serve", "裤":"trousers; pants", "裙":"skirt", "鞋":"shoe",
    "帽":"hat; cap", "袜":"socks; stockings", "包":"bag; package; wrap", "箱":"box; trunk; case",
    "床":"bed", "桌":"table; desk", "椅":"chair", "柜":"cabinet; wardrobe", "灯":"lamp; light",
    "窗":"window", "墙":"wall", "房":"house; room; building", "屋":"house; room", "楼":"building; floor; tower",
    "街":"street", "路":"road; way; path", "桥":"bridge", "车":"car; vehicle", "轮":"wheel; round",
    "船":"boat; ship", "机":"machine; aircraft", "飞":"fly", "行":"go; travel; line", "走":"walk; go",
    "跑":"run", "跳":"jump; skip", "站":"stand; station", "坐":"sit", "睡":"sleep", "醒":"wake; sober",
    "吃":"eat", "喝":"drink", "吸":"inhale; absorb; suck", "呼":"exhale; call; shout", "说":"say; speak; talk",
    "讲":"speak; explain", "读":"read; study; read aloud", "写":"write", "画":"draw; paint; picture",
    "听":"listen; hear; obey", "看":"see; look; watch; read", "望":"look far; hope; expect",
    "见":"see; meet; appear", "想":"think; want; miss", "念":"read; think; miss; idea", "思":"think; thought; miss",
    "忆":"remember; recall", "记":"remember; record; note", "忘":"forget", "懂":"understand; know",
    "知":"know; knowledge; aware", "道":"way; road; say; doctrine", "理":"reason; manage; texture",
    "解":"understand; untie; explain", "决":"decide; resolve; execute", "定":"decide; fix; definite",
    "选":"choose; select; elect", "择":"choose; select", "挑":"pick; choose; carry", "用":"use; useful; expense",
    "使":"make; use; envoy", "拿":"take; hold; seize", "给":"give; for; supply", "送":"send; give; deliver",
    "寄":"send; mail; lodge", "收":"receive; collect", "发":"send; emit; hair; develop", "到":"arrive; reach; go to",
    "来":"come; arrive; future", "去":"go; leave; past", "回":"return; back; answer", "进":"enter; advance",
    "出":"out; exit; produce", "上":"up; on; previous; go up", "下":"down; under; next; go down",
    "前":"front; before; forward", "后":"back; after; behind; rear", "左":"left", "右":"right",
    "内":"inside; inner; internal", "外":"outside; outer; foreign", "里":"inside; in; mile; neighborhood",
    "间":"between; room; interval", "旁":"side; beside", "边":"side; edge; border", "这":"this; these",
    "那":"that; those", "哪":"which; where", "谁":"who; whom", "什":"what; ten", "么":"what (suffix)",
    "为":"for; because; do; act", "以":"with; by; in order to; think", "从":"from; follow; through",
    "向":"toward; face; direction", "往":"go; toward; past", "于":"in; at; for; on", "与":"and; with; give",
    "和":"and; with; harmony; sum", "及":"and; reach; up to", "或":"or; perhaps; maybe", "因":"cause; because; reason",
    "果":"fruit; result; effect", "所":"place; that which; so", "多":"many; much; more; many", "少":"few; little; young; lack",
    "几":"several; how many; table", "很":"very; quite", "太":"too; very; extreme", "最":"most; best; -est",
    "更":"more; even more; change", "越":"more; exceed; cross", "都":"all; both; even; capital", "全":"all; whole; complete",
    "半":"half; semi-", "总":"total; always; general", "共":"common; together; altogether", "同":"same; together; with",
    "各":"each; various; every", "别":"other; separate; don't", "另":"another; other; separately", "再":"again; once more",
    "又":"again; also", "还":"still; also; return; pay back", "就":"just; then; approach", "才":"only; just; talent",
    "刚":"just; exactly; firm; rigid", "正":"right; correct; upright; main", "反":"opposite; reverse; anti-", "对":"correct; right; pair; toward",
    "错":"wrong; mistake; error", "没":"not have; no; not", "不":"not; no", "无":"no; not; without; nothing",
    "有":"have; there is; possess", "非":"not; wrong; non-", "是":"is; yes; correct", "在":"at; in; exist; be located",
    "从":"from; follow", "自":"self; from; since; naturally", "己":"oneself; own", "我":"I; me; my",
    "你":"you", "他":"he; him; other", "她":"she; her", "它":"it; its", "们":"(plural suffix)",
    "咱":"we; us", "这":"this", "那":"that", "个":"individual; piece; (measure word)", "位":"position; place; seat; digit",
    "只":"only; just; single; measure word", "条":"strip; article; measure word", "张":"sheet; open; spread; measure word",
    "片":"piece; slice; film", "块":"piece; lump; block; dollar", "件":"piece; item; letter", "项":"item; term; nape",
    "样":"kind; appearance; sample", "种":"kind; type; plant; seed", "类":"kind; category; class; similar",
    "型":"type; model; mold", "式":"type; style; formula; ceremony", "样":"kind; sample; style", "态":"state; attitude; form",
    "形":"shape; form; appear", "状":"state; shape; condition", "色":"color; look; scene; quality", "彩":"color; brilliance; prize",
    "颜":"face; color; complexion", "料":"material; expect; feed", "材":"material; timber; talent", "源":"source; origin; resource",
    "资":"capital; resources; support", "本":"book; basis; capital; this", "基":"base; foundation; basic", "础":"foundation; plinth",
    "根":"root; basis; foundation", "底":"bottom; base; background", "顶":"top; peak; carry on head", "层":"layer; floor; level",
    "级":"level; grade; step; class", "阶":"steps; rank; class", "段":"section; paragraph; stage", "期":"period; phase; expect",
    "届":"session; term; class", "批":"batch; criticize", "组":"group; organize; set", "队":"team; queue; line",
    "伍":"squad; five; company", "班":"class; squad; shift", "团":"group; regiment; round; reunion", "社":"society; agency",
    "会":"meeting; can; will; association", "议":"discuss; opinion; proposal", "论":"discuss; theory; treatise", "谈":"talk; chat; discuss",
    "讲":"speak; explain; lecture", "评":"comment; evaluate; judge", "审":"examine; judge; trial", "批":"criticize; batch; approve",
    "准":"allow; standard; accurate", "许":"allow; permit; maybe; promise", "允":"allow; permit; consent", "拒":"refuse; reject; ward off",
    "绝":"absolute; cut off; reject; extreme", "接":"connect; receive; welcome; catch", "受":"receive; suffer; accept; endure",
    "给":"give; supply; for", "与":"and; with; give", "及":"and; reach; up to", "并":"and; combine; side by side",
    "且":"and; moreover; even", "而":"and; but; while", "故":"therefore; reason; old", "此":"this; here; thus",
    "彼":"that; the other; there", "次":"time; next; second; order", "第":"number; sequence; (ordinal)", "号":"number; mark; name",
    "编":"number; compile; edit; weave", "序":"order; sequence; preface", "列":"list; row; arrange; line", "排":"row; arrange; line; discharge",
    "按":"press; according to; check", "据":"according to; evidence; occupy", "照":"according to; shine; photo; look", "依":"according to; depend; rely",
    "靠":"lean; depend; near; rely on", "赖":"depend; rely; deny", "凭":"rely on; proof; evidence", "借":"borrow; lend; use; by means of",
    "假":"fake; false; holiday; borrow", "利":"sharp; profit; benefit", "弊":"harm; disadvantage; cheat", "害":"harm; damage; disaster",
    "损":"lose; damage; harm", "益":"benefit; profit; increase", "增":"increase; add; gain", "减":"reduce; decrease; subtract",
    "加":"add; plus; increase; join", "倍":"times; double; fold", "除":"divide; remove; except; eliminate", "乘":"multiply; ride; take advantage of",
    "数":"number; count; several", "学":"learn; study; subject", "问":"ask; question; inquire", "答":"answer; reply; respond",
    "应":"should; answer; respond; apply", "回":"return; reply; circle", "复":"repeat; reply; recover; again", "测":"measure; test; survey",
    "试":"test; try; attempt; exam", "验":"test; verify; examine; effective", "查":"check; investigate; examine", "检":"check; inspect; examine",
    "看":"see; look; watch; consider", "观":"observe; view; concept; outlook", "察":"examine; observe; inspect", "审":"examine; try; careful; trial",
    "核":"check; nucleus; core; examine", "证":"prove; evidence; certificate; verify", "明":"clear; bright; prove; explain", "实":"real; true; solid; actual",
    "践":"practice; fulfill; tread", "行":"go; walk; do; line; bank", "动":"move; act; motion; touch", "作":"do; make; work; write",
    "操":"operate; hold; drill; exercise", "纵":"vertical; release; indulge; commander", "控":"control; accuse; charge", "制":"make; control; system; restrict",
    "限":"limit; bound; restrict", "量":"measure; quantity; amount", "规":"rule; regulate; plan; compass", "范":"norm; range; pattern; model",
    "则":"rule; then; standard; principle", "律":"law; rule; discipline; restrain", "制":"system; manufacture; control", "度":"degree; measure; system; tolerance",
    "格":"grid; standard; case; style", "局":"bureau; situation; game; part", "面":"face; side; surface; aspect; noodles", "点":"point; dot; spot; a little",
    "线":"line; thread; wire; route", "面":"face; surface; aspect; side", "体":"body; substance; form; system", "系":"system; department; tie; series",
    "统":"unite; system; overall; command", "结":"tie; knot; conclusion; unite", "构":"construct; structure; compose", "成":"become; complete; succeed; achieve",
    "功":"achievement; merit; skill; function", "效":"effect; result; efficacy; imitate", "能":"can; ability; energy; capable", "力":"power; force; strength; ability",
    "量":"quantity; amount; volume", "数":"number; count; several; math", "据":"evidence; according to; occupy", "库":"warehouse; library; database; bank",
    "存":"save; store; deposit; exist", "取":"take; get; fetch; select", "读":"read; study; pronounce", "写":"write; compose; describe",
    "编":"compile; edit; weave; arrange", "程":"procedure; journey; range; process", "序":"order; sequence; program; preface", "库":"library; warehouse; repository",
    "集":"collect; gather; set; collection", "聚":"gather; assemble; focus", "合":"close; combine; fit; unite", "并":"combine; merge; and; also",
    "通":"through; open; communicate; general", "网":"net; network; web", "络":"network; connect; collateral", "联":"unite; join; connect; ally",
    "互":"mutual; each other", "交":"hand over; cross; exchange; friendship", "流":"flow; stream; class; spread", "传":"pass; spread; transmit; biography",
    "输":"transport; transmit; lose", "送":"send; give; deliver; escort", "接":"connect; receive; meet; catch", "收":"receive; collect; harvest; accept",
    "布":"cloth; spread; announce; arrange", "置":"place; put; set up; buy", "配":"match; allocate; configure; spouse", "套":"suit; set; cover; sleeve",
    "批":"batch; criticize; wholesale", "次":"time; order; next; secondary", "处":"place; deal with; locate; department", "所":"place; location; office; that which",
    "相":"each other; mutual; appearance; photo", "对":"toward; correct; opposite; pair", "比":"compare; ratio; contrast; ratio", "较":"compare; comparatively; fairly",
    "差":"difference; poor; error; send", "距":"distance; apart from; distance", "离":"leave; distance; separate; depart", "分":"divide; separate; minute; point",
    "合":"combine; close; whole; suitable", "总":"total; always; general; summarize", "小":"small; little; young; minor", "大":"big; large; great; major",
    "老":"old; aged; experienced; always", "幼":"young; childish; infant", "青":"green; blue; young; youth", "年":"year; age; new year",
    "岁":"year (of age); year; harvest", "今":"today; now; current", "昨":"yesterday", "明":"bright; tomorrow; clear; understand",
    "昨":"yesterday", "今":"now; today; current", "昨":"yesterday", "天":"day; sky; heaven; weather", "地":"earth; ground; land; place",
    "时":"time; hour; when; opportunity", "间":"between; interval; room; space", "刻":"moment; carve; quarter; engrave", "钟":"bell; clock; time; hour",
    "秒":"second; second (unit)", "分":"minute; divide; point; score", "周":"week; circle; surround; Zhou", "月":"month; moon", "年":"year; age",
    "季":"season; quarter; youngest brother", "节":"festival; section; joint; save", "假":"holiday; vacation; fake; borrow", "日":"day; sun; date; daily",
    "期":"period; date; expect; phase", "末":"end; final; powder; details", "初":"beginning; initial; first; elementary", "底":"bottom; end; base; background",
    "近":"near; close; recent; almost", "远":"far; distant; remote", "久":"long time; long-lasting", "永":"forever; eternal; permanent",
    "暂":"temporary; for the time being; brief", "临":"face; approach; temporary; at the point of", "即":"namely; even if; immediate; approach", "将":"will; shall; general; future; take",
    "未":"not yet; future; wei (branch)", "已":"already; stop; cease; finish", "曾":"once; already; ever; (surname)", "常":"often; common; constant; regular",
    "频":"frequently; frequency; repeatedly", "屡":"repeatedly; often; frequently", "往":"go; toward; past; former", "昔":"former times; past; ancient",
    "古":"ancient; old; age-old", "现":"present; now; appear; existing", "代":"generation; era; dynasty; substitute", "当":"when; should; equal; current; at",
    "前":"front; before; previous; ahead", "后":"back; after; behind; later", "先":"first; before; earlier; ancestors", "早":"early; morning; ago; soon",
    "午":"noon; 11am-1pm", "夜":"night; late night", "晚":"evening; night; late; junior", "晨":"morning; dawn; daybreak",
    "朝":"morning; dynasty; toward; court", "夕":"evening; dusk; sunset; night", "暮":"dusk; evening; late; twilight",
}

# 热词/常用词组英译（覆盖互联网/科技/生活高频词）
PHRASES = {
    "云计算":"cloud computing", "人工智能":"artificial intelligence", "算力":"computing power",
    "大数据":"big data", "云端":"cloud", "互联网":"internet", "物联网":"Internet of Things",
    "区块链":"blockchain", "算法":"algorithm", "程序":"program", "软件":"software", "硬件":"hardware",
    "电脑":"computer", "手机":"mobile phone", "应用":"app; application", "用户":"user", "账户":"account",
    "密码":"password", "登录":"login", "注册":"register", "下载":"download", "上传":"upload",
    "联网":"go online", "服务器":"server", "网络":"network", "安全":"security; safe", "隐私":"privacy",
    "数据":"data", "信息":"information", "知识":"knowledge", "技术":"technology", "科技":"science and technology",
    "创新":"innovation", "创业":"start a business", "投资":"investment", "融资":"financing", "股权":"equity; stock rights",
    "利润":"profit", "营收":"revenue", "成本":"cost", "效率":"efficiency", "质量":"quality",
    "体验":"experience", "设计":"design", "开发":"development", "测试":"testing", "上线":"go live; launch",
    "版本":"version", "更新":"update", "发布":"release; publish", "开源":"open source", "代码":"code",
    "编程":"programming", "接口":"interface; API", "数据库":"database", "存储":"storage", "备份":"backup",
    "同步":"synchronize", "异步":"asynchronous", "实时":"real-time", "在线":"online", "离线":"offline",
    "远程":"remote", "本地":"local", "端到端":"end-to-end", "延迟":"latency; delay", "带宽":"bandwidth",
    "流量":"traffic; data usage", "信号":"signal", "芯片":"chip", "处理器":"processor", "内存":"memory",
    "硬盘":"hard disk", "显卡":"graphics card", "系统":"system", "平台":"platform", "生态":"ecosystem",
    "社区":"community", "论坛":"forum", "群组":"group", "消息":"message", "通知":"notification",
    "聊天":"chat", "视频":"video", "音频":"audio", "图片":"image; picture", "文档":"document",
    "表格":"table; spreadsheet", "邮件":"email", "日历":"calendar", "日程":"schedule", "会议":"meeting",
    "任务":"task", "项目":"project", "团队":"team", "公司":"company", "企业":"enterprise",
    "创业公司":"startup", "上市":"go public; listed", "市值":"market value", "融资":"financing",
    "估值":"valuation", "商业模式":"business model", "市场需求":"market demand", "竞争力":"competitiveness",
    "优势":"advantage", "劣势":"disadvantage", "机会":"opportunity", "挑战":"challenge", "风险":"risk",
    "趋势":"trend", "未来":"future", "愿景":"vision", "使命":"mission", "价值":"value",
    "战略":"strategy", "规划":"planning", "执行":"execution", "管理":"management", "运营":"operation",
    "营销":"marketing", "销售":"sales", "客户":"customer", "用户":"user", "产品":"product",
    "服务":"service", "方案":"solution; plan", "标准":"standard", "规范":"specification; norm",
    "流程":"process; workflow", "制度":"institution; system", "规则":"rules", "政策":"policy",
    "法律":"law", "合规":"compliance", "监管":"regulation; supervision", "审计":"audit",
    "报告":"report", "分析":"analysis", "统计":"statistics", "预测":"forecast; prediction",
    "决策":"decision-making", "优化":"optimization", "提升":"improve; upgrade", "改进":"improvement",
    "修复":"fix; repair", "维护":"maintenance", "支持":"support", "帮助":"help", "教程":"tutorial",
    "指南":"guide", "文档":"documentation", "说明":"description; explanation", "常见问题":"FAQ",
    "客服":"customer service", "售后":"after-sales", "退款":"refund", "订单":"order", "支付":"payment",
    "购物":"shopping", "电商":"e-commerce", "快递":"express delivery", "物流":"logistics", "仓库":"warehouse",
    "库存":"inventory", "供应链":"supply chain", "生产":"production", "制造":"manufacturing", "工厂":"factory",
    "设备":"equipment", "机器":"machine", "自动化":"automation", "机器人":"robot", "驾驶":"driving",
    "汽车":"car; automobile", "电动":"electric", "能源":"energy", "电力":"electric power", "电池":"battery",
    "充电":"charge", "环保":"environmental protection", "绿色":"green", "可持续":"sustainable",
    "教育":"education", "学校":"school", "老师":"teacher", "学生":"student", "课程":"course; curriculum",
    "考试":"exam; test", "成绩":"score; achievement", "毕业":"graduate", "学位":"degree",
    "健康":"health", "医疗":"medical care", "医院":"hospital", "医生":"doctor", "护士":"nurse",
    "病人":"patient", "治疗":"treatment", "手术":"surgery", "药物":"medicine; drug", "疫苗":"vaccine",
    "营养":"nutrition", "运动":"sports; exercise", "健身":"fitness", "跑步":"running; jogging",
    "旅游":"travel; tourism", "旅行":"travel; trip", "景点":"scenic spot", "酒店":"hotel", "机票":"air ticket",
    "航班":"flight", "机场":"airport", "高铁":"high-speed rail", "地铁":"subway; metro", "公交":"bus",
    "出租":"taxi; rent", "地图":"map", "导航":"navigation", "位置":"location; position", "地址":"address",
    "天气":"weather", "温度":"temperature", "预报":"forecast", "台风":"typhoon", "地震":"earthquake",
    "洪水":"flood", "干旱":"drought", "消防":"firefighting", "警察":"police", "救援":"rescue",
    "新闻":"news", "媒体":"media", "记者":"reporter", "采访":"interview", "直播":"live streaming",
    "短视频":"short video", "视频":"video", "音乐":"music", "电影":"movie; film", "电视剧":"TV series",
    "游戏":"game", "玩家":"player; gamer", "主播":"streamer; anchor", "粉丝":"fans", "点赞":"like",
    "评论":"comment", "转发":"share; repost", "收藏":"favorite; bookmark", "关注":"follow; attention",
    "分享":"share", "发布":"publish; post", "内容":"content", "创作":"creation", "作者":"author; creator",
    "版权":"copyright", "专利":"patent", "商标":"trademark", "知识产权":"intellectual property",
    "合同":"contract", "协议":"agreement", "条款":"terms; clause", "签字":"signature", "盖章":"seal; stamp",
    "发票":"invoice", "收据":"receipt", "报销":"reimbursement", "工资":"salary; wage", "奖金":"bonus",
    "社保":"social insurance", "公积金":"housing fund", "退休":"retirement", "养老":"pension; elderly care",
    "保险":"insurance", "赔偿":"compensation", "诉讼":"lawsuit; litigation", "律师":"lawyer; attorney",
    "法院":"court", "证据":"evidence", "判决":"judgment; verdict", "执行":"execution; enforcement",
    "诚信":"integrity; honesty", "信用":"credit; trust", "道德":"morality; ethics", "责任":"responsibility",
    "义务":"obligation; duty", "权利":"right", "自由":"freedom; liberty", "平等":"equality",
    "公正":"fairness; justice", "和平":"peace", "发展":"development", "进步":"progress", "文明":"civilization",
    "文化":"culture", "历史":"history", "传统":"tradition", "现代":"modern", "当代":"contemporary",
    "未来":"future", "宇宙":"universe; cosmos", "星球":"planet; star", "地球":"Earth", "太阳":"sun",
    "月亮":"moon", "星星":"star", "天空":"sky", "空气":"air", "环境":"environment", "自然":"nature",
    "资源":"resources", "矿产":"minerals", "石油":"petroleum; oil", "煤炭":"coal", "钢铁":"steel",
    "金属":"metal", "塑料":"plastic", "木材":"wood; timber", "纸张":"paper", "垃圾":"garbage; trash",
    "回收":"recycle; retrieve", "清洁":"clean; cleaning", "城市":"city", "农村":"rural area; countryside",
    "国家":"country; nation", "政府":"government", "人民":"people", "社会":"society", "经济":"economy",
    "政治":"politics", "军事":"military", "外交":"diplomacy", "国际":"international", "全球":"global",
    "世界":"world", "亚洲":"Asia", "欧洲":"Europe", "非洲":"Africa", "美洲":"Americas",
    "美国":"United States; America", "英国":"United Kingdom; Britain", "法国":"France", "德国":"Germany",
    "日本":"Japan", "韩国":"South Korea", "印度":"India", "俄罗斯":"Russia", "澳洲":"Australia",
    "加拿大":"Canada", "巴西":"Brazil", "非洲":"Africa", "北京":"Beijing", "上海":"Shanghai",
    "广州":"Guangzhou", "深圳":"Shenzhen", "香港":"Hong Kong", "澳门":"Macao; Macau", "台湾":"Taiwan",
    "汉语":"Chinese language", "中文":"Chinese", "英文":"English", "日语":"Japanese", "翻译":"translation; translate",
    "语言":"language", "文字":"writing; characters", "汉字":"Chinese characters", "拼音":"pinyin",
    "五笔":"Wubi (input method)", "输入法":"input method", "键盘":"keyboard", "打字":"typing",
    "学习":"study; learning", "练习":"practice; exercise", "复习":"review; revise", "理解":"understand; comprehension",
    "记忆":"memory", "思考":"thinking; think", "判断":"judgment; determine", "推理":"reasoning; inference",
    "逻辑":"logic", "数学":"mathematics", "物理":"physics", "化学":"chemistry", "生物":"biology",
    "地理":"geography", "历史":"history", "哲学":"philosophy", "心理":"psychology", "经济":"economics",
    "金融":"finance", "会计":"accounting", "管理":"management", "市场":"market", "销售":"sales",
    "广告":"advertisement", "品牌":"brand", "口碑":"reputation; word of mouth", "体验":"experience",
    "满意度":"satisfaction", "忠诚度":"loyalty", "复购":"repurchase", "转化率":"conversion rate",
    "留存":"retention", "增长":"growth", "扩张":"expansion", "规模":"scale; size", "利润":"profit",
    "亏损":"loss", "盈利":"profitable", "亏损":"loss; deficit", "现金流":"cash flow", "负债":"debt; liability",
    "资产":"assets", "收入":"income; revenue", "支出":"expenditure; expenses", "预算":"budget",
    "采购":"procurement; purchasing", "供应":"supply", "需求":"demand; requirement", "供给":"supply",
    "价格":"price", "价值":"value", "质量":"quality", "数量":"quantity", "时间":"time",
    "空间":"space", "速度":"speed", "频率":"frequency", "精度":"precision; accuracy", "成本":"cost",
    "效率":"efficiency", "效果":"effect; result", "收益":"return; gain", "回报":"return; reward",
    "投资回报":"return on investment", "风险":"risk", "不确定":"uncertain", "确定":"certain; definite",
    "可能":"possible; maybe", "必然":"inevitable; certain", "偶然":"accidental; by chance",
}

# 合并并去重（词组优先）
merged = {}
merged.update(SINGLE)
merged.update(PHRASES)

with open("/home/user/Doubao/chats/38437785566515714/CloudWubi/cloudwubi-gateway/en_dict.json", "w", encoding="utf-8") as f:
    json.dump(merged, f, ensure_ascii=False, indent=0)

print(f"词典生成完成：{len(merged)} 条")
